

# clubs, spades, diamonds, hearts
cardDictiony = {1: "Ace of Clubs",
                2: "Two of Clubs",
                3: "Three of Clubs",
                4: "Four of Clubs",
                5: "Five of Clubs",
                6: "Six of Clubs",
                7: "Seven of Clubs",
                8: "Eight of Clubs",
                9: "Nine of Clubs",
                10: "Ten of Clubs",
                11: "Jack of Clubs",
                12: "Queen of Clubs",
                13: "King of Clubs",
                14: "Ace of Spades",
                15: "Two of Spades",
                16: "Three of Spades",
                17: "Four of Spades",
                18: "Five of Spades",
                19: "Six of Spades",
                20: "Seven of Spades",
                21: "Eight of Spades",
                22: "Nine of Spades",
                23: "Ten of Spades",
                24: "Jack of Spades",
                25: "Queen of Spades",
                26: "King of Spades",
                27: "Ace of Diamonds",
                28: "Two of Diamonds",
                29: "Three of Diamonds",
                30: "Four of Diamonds",
                31: "Five of Diamonds",
                32: "Six of Diamonds",
                33: "Seven of Diamonds",
                34: "Eight of Diamonds",
                35: "Nine of Diamonds",
                36: "Ten of Diamonds",
                37: "Jack of Diamonds",
                38: "Queen of Diamonds",
                39: "King of Diamonds",
                40: "Ace of Hearts",
                41: "Two of Hearts",
                42: "Three of Hearts",
                43: "Four of Hearts",
                44: "Five of Hearts",
                45: "Six of Hearts",
                46: "Seven of Hearts",
                47: "Eight of Hearts",
                48: "Nine of Hearts",
                49: "Ten of Hearts",
                50: "Jack of Hearts",
                51: "Queen of Hearts",
                52: "King of Hearts",
                }

#print(cardDictiony)  # for testing dictionary